#!/bin/bash

bucket_name='a-bucket-name'
# website_directory must be the path to the folder that contains your index.html file
website_directory='/path/to/website/' 
region='us-west-2'
profile='Playground'

# 1. Create a new bucket with a unique name
aws s3 mb --profile $profile --region $region "s3://$bucket_name"

# 2. Upload you website
aws s3 sync --profile $profile --region $region $website_directory "s3://$bucket_name/"
